from Command import Command
from Add import Add
from ChangePass import ChangePass
from Delkey import Delkey
from Exit import Exit
from Help import Help
from Keys import Keys
from Modify import Modify
from Remove import Remove
from Rows import Rows
from Value import Value
